#FROM jupyter/scipy-notebook

#MAINTAINER Jupyter Project <jupyter@googlegroups.com>

# Install Python 2 Tensorflow
# RUN conda install --quiet --yes -n python2 'tensorflow=1.0.1'
RUN sudo docker pull qianmao/cs503_tensorflow_jupyter
